/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.event.KeyEvent;
import net.miginfocom.swing.MigLayout;
import proyecto2.Objetos.CarpetaObj;



public class Carpeta extends javax.swing.JPanel {

    
    private boolean selected;
    private boolean open;
    String realNombre, shownNombre;
    private CarpetaObj carpeta;
    public Carpeta() {
        initComponents();
    }
    public Carpeta(CarpetaObj carpeta){
        initComponents();
        realNombre = carpeta.getNombre();
        shownNombre = generateSNombre(realNombre);
        jToggleButton1.setText(shownNombre);
        this.carpeta = carpeta;
        open = false;
        selected = false;
    }
    
    private void mLayout() {
        MigLayout m = new MigLayout("", "80:80:80", "80:80:80");
        this.removeAll();
        this.setLayout(m);
        this.add(jToggleButton1);
    }

    private String generateSNombre(String nombre) {
        if (nombre.length() > 12) {
            nombre = nombre.substring(0, 9) + "...";
        }
        return nombre;
    }   
    
    public void setOpen(boolean open){
        this.open = open;
    }
    
    public void setSelected(boolean select){
        this.selected = select;
        jToggleButton1.setSelected(select);
    }
    
    public boolean isOpened(){
        return open;
    }
    
    public boolean isSelected(){
        return selected;
    }
    
    public CarpetaObj getCarpeta(){
        return carpeta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(59, 52, 51));
        setForeground(new java.awt.Color(59, 52, 51));
        setPreferredSize(new java.awt.Dimension(70, 73));

        jToggleButton1.setBackground(new java.awt.Color(59, 52, 51));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 242));
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Icons/Folder.png"))); // NOI18N
        jToggleButton1.setText("Carpeta");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setMaximumSize(new java.awt.Dimension(70, 73));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(70, 73));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(70, 73));
        jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseReleased
        if(evt.getClickCount() == 2){
            setOpen(true);
            setSelected(false);
            this.getParent().requestFocus();
        }else{
            setSelected(true);
            this.getParent().requestFocus();
        }
    }//GEN-LAST:event_jToggleButton1MouseReleased
    
    public void setText(String text){
        realNombre = text;
        jToggleButton1.setText(text);
        carpeta.setNombre(realNombre);
    }
    
    public String getText(){
        return realNombre;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
