/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import net.miginfocom.swing.MigLayout;



public class ImageViewer extends javax.swing.JFrame {

    String imgPath;
    public ImageViewer(String imgPath) {
        initComponents();
        this.imgPath = imgPath;
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        mLayout();
        placeImage(1);
    }
    
    private void placeImage(int i){
        File file = new File(imgPath);
        try {
            Image imagen = ImageIO.read(file);
            ImageIcon icon = new ImageIcon(imagen);
            lblImg.setIcon(icon);
        } catch (IOException ex) {
            try {
                System.out.println("wat: "+i);
                Thread.sleep(500);
                placeImage(i+1);
            } catch (InterruptedException ex1) {
                Logger.getLogger(ImageViewer.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }
    
    private Image ZoomImage(int w, int h, Image img){
        BufferedImage buf = new BufferedImage(w, h,BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = buf.createGraphics();
        g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2d.drawImage(img, 0,0,w,h,null);
        g2d.dispose();
        
        return buf;
    }
    
    private void mLayout(){
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int w = d.width;
        int h = d.height;
        int c = w/5;
        int r = (2*c)-200;
        this.setSize(w, h-100);
        MigLayout m = new MigLayout("", "["+c+"]["+c+"][100][100]["+(r)+"]", "[][][]");   
        jPanel1.setLayout(m);
        
        
        jPanel1.add(jScrollPane2, "width "+w+", height "+h+",span 5");
        jPanel1.add(inBut, "cell 2 1");
        jPanel1.add(outBut, "cell 3 1 ");
        

        jScrollPane2.setViewportView(contImagen);
        MigLayout m2 = new MigLayout();
        contImagen.setLayout(m2);
        contImagen.add(lblImg);
        System.out.println(lblImg.getIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        outBut = new javax.swing.JButton();
        inBut = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        contImagen = new javax.swing.JPanel();
        lblImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(59, 52, 51));

        outBut.setBackground(new java.awt.Color(59, 52, 51));
        outBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Icons/zoomout.png"))); // NOI18N
        outBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        outBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outButActionPerformed(evt);
            }
        });

        inBut.setBackground(new java.awt.Color(59, 52, 51));
        inBut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Icons/zoomin.png"))); // NOI18N
        inBut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        inBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inButActionPerformed(evt);
            }
        });

        contImagen.setBackground(new java.awt.Color(59, 52, 51));

        javax.swing.GroupLayout contImagenLayout = new javax.swing.GroupLayout(contImagen);
        contImagen.setLayout(contImagenLayout);
        contImagenLayout.setHorizontalGroup(
            contImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contImagenLayout.createSequentialGroup()
                .addComponent(lblImg)
                .addGap(0, 398, Short.MAX_VALUE))
        );
        contImagenLayout.setVerticalGroup(
            contImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contImagenLayout.createSequentialGroup()
                .addComponent(lblImg)
                .addGap(0, 234, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(contImagen);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(inBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outBut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inBut)
                    .addComponent(outBut))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void outButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outButActionPerformed
        try{
            int w = lblImg.getWidth();
            int h = lblImg.getHeight();
            File file = new File(imgPath);
            Image img = ImageIO.read(file);
            ImageIcon icon = new ImageIcon(ZoomImage(w-100, h-100, img));
            lblImg.setIcon(icon);
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_outButActionPerformed

    private void inButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inButActionPerformed
            int w = lblImg.getWidth();
            int h = lblImg.getHeight();
            File file = new File(imgPath);
            Image img;
        try {
            img = ImageIO.read(file);
            ImageIcon icon = new ImageIcon(ZoomImage(w+100, h+100, img));
            lblImg.setIcon(icon);            
        } catch (IOException ex) {
            Logger.getLogger(ImageViewer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_inButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageViewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageViewer("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contImagen;
    private javax.swing.JButton inBut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImg;
    private javax.swing.JButton outBut;
    // End of variables declaration//GEN-END:variables
}
